### PR TITLE
Sorting clusters, finding k peaks, new plots

### PR DESCRIPTION
**Pull request by EricArcher**
I've changed the findClusters function to
 1) have the options of finding the top 'k' peaks based on gamma value
 2) sort clusters based on peak gamma value

I've also added some different plotting functions for the three main kinds of plots (decision, gamma, and MDS graphs), along with one that combines all three.

### CODE REVIEW

**Comment by thomasp85** [comment]
Can you add a clear description of the different plotting functions and their use to the documentation? As it is now the user is a bit at a loss...

**Comment by EricArcher** [comment]
Will do.


----

*Eric Archer, Ph.D.*
Southwest Fisheries Science Center
NMFS, NOAA
8901 La Jolla Shores Drive
La Jolla, CA 92037 USA
858-546-7121 (work)
858-546-7003 (FAX)

Marine Mammal Genetics Group: swfsc.noaa.gov/mmtd-mmgenetics
ETP Cetacean Assessment Program: swfsc.noaa.gov/mmtd-etp

"


*The universe doesn't care what you believe. The wonderful thing about
science is that it   doesn't ask for your faith, it just asks   for your
eyes.*"  - Randall Munroe

"*Lighthouses are more helpful than churches.*"
   - Benjamin Franklin

   "*...but I'll take a GPS over either one.*"
       - John C. "Craig" George

**Comment by EricArcher** [comment]
I overwrote the existing plotting functions and updated the documentation so there wouldn't be confusion/duplication in plotting. There is now just a single "new" function (plotDensClust) that creates a single figure of all three plots. Feel free to rename it if you like. Thanks!

**Comment by thomasp85** [comment]
Why did you change plotMDS from being an S3 generic?

**Comment by EricArcher** [comment]
I think it was because I was having documentation compile problems with it
as an S3 generic and I didn't know of another plotMDS generic that it
needed to coexist with. I'm sorry if I missed something and will happily
change it back.


----

*Eric Archer, Ph.D.*
Southwest Fisheries Science Center
NMFS, NOAA
8901 La Jolla Shores Drive
La Jolla, CA 92037 USA
858-546-7121 (work)
858-546-7003 (FAX)

Marine Mammal Genetics Group: swfsc.noaa.gov/mmtd-mmgenetics
ETP Cetacean Assessment Program: swfsc.noaa.gov/mmtd-etp

"


*The universe doesn't care what you believe. The wonderful thing about
science is that it   doesn't ask for your faith, it just asks   for your
eyes.*"  - Randall Munroe

"*Lighthouses are more helpful than churches.*"
   - Benjamin Franklin

   "*...but I'll take a GPS over either one.*"
       - John C. "Craig" George

**Comment by EricArcher** [comment]
Have you had time to review the last edits?

**Comment by thomasp85** [comment]
Yes and no. I've decided that I want a different API for the plots but haven't had time to give it any more thoughts. My deadline is next Friday (will probably run over a bit) and once I've handed in my dissertation I'll give my other packages some well deserved attention

**Comment by EricArcher** [comment]
Gotcha. I really like your implementation of this algorithm, so If you
would like any help the coding (e.g., re-coding in ggplot2), I'd be happy
to contribute / collaborate.

Good luck with your dissertation!

Cheers,
Eric


----

*Eric Archer, Ph.D.*
Southwest Fisheries Science Center
NMFS, NOAA
8901 La Jolla Shores Drive
La Jolla, CA 92037 USA
858-546-7121 (work)
858-546-7003 (FAX)

Marine Mammal Genetics Group: swfsc.noaa.gov/mmtd-mmgenetics
ETP Cetacean Assessment Program: swfsc.noaa.gov/mmtd-etp
https://github/ericarcher

"


*The universe doesn't care what you believe. The wonderful thing about
science is that it   doesn't ask for your faith, it just asks   for your
eyes.*"  - Randall Munroe

"*Lighthouses are more helpful than churches.*"
   - Benjamin Franklin

   "*...but I'll take a GPS over either one.*"
       - John C. "Craig" George

**Comment by thomasp85** [comment]
Thanks - I'll reach out if needed...

**Comment by thomasp85** [comment]
Ok - I'm a doctor now :-)

I've had some time to go through the PR again with fresh eyes.

The k-peaks implementation is fine and can be merged in. I would like for the new plotting functions to be implemented as separate functions rather than options in the main plot. Maybe an additional plotting function that makes a composition of the different plot types...

There is another PR that is almost ready for merging and that will touch on some of the same code areas. Would you be interested in having a new go at this once the other PR has been merged?

**Comment by EricArcher** [comment]
Congrats on the new letters! :clap: I hope you're able to take some time off to relax and enjoy your new status. :crown:

I'm perfectly happy waiting until the other PR goes through and then will do another one with the plotting functions as separate entities.

**Comment by thomasp85** [comment]
Perfect - thanks

**Pull request closed without merging**
