### PR TITLE
Simple efficiency improvement

### PR DESCRIPTION
**Pull request by seaaan**
Hej Thomas

Changing this line of code makes `densityClust()` run 2-3X faster while giving identical results. The details are below, but profiling showed that `estimateDc()` was taking the most time and I figured out a more efficient way to do the same calculation. See https://gist.github.com/seaaan/8120969164b5e51185af for how I measured performance.

God weekend! 

-----------------------------------------------------------------------------------------------------------------------------

Current implementation:
1. Create logical matrix for comb < dc
2. Calculate vector of row sums
3. Subtract 1 from each element of row-sum vector
4. Divide each element of row-sum vector by size
5. Calculate the mean of the row-sum vector

Improved implementation:
1. Create logical matrix for comb < dc
2. Calculate matrix sum (scalar)
3. Divide matrix sum by number of rows of matrix to get mean (scalar)
4. Subtract 1 from mean
5. Divide mean by size

~2-3 fold speedup. See https://gist.github.com/seaaan/8120969164b5e51185af for profiling results.

### CODE REVIEW

**Comment by seaaan** [comment]
If you're interested, I've also found some other, smaller ways to speed up the code about another 2-fold without doing anything too dramatic, but I thought I'd keep the proposed change minor to start.

**Comment by thomasp85** [comment]
Thanks - sure I'll look into this and your other proposals. I'm currently suffering a concussion so it'll have to wait a bit though...

**Comment by seaaan** [comment]
Yikes, sorry to hear about the concussion. God bedring!

**Comment by seaaan** [comment]
Hi Thomas,
I hope you're starting to feel better from your concussion. I just wanted to check in and see whether you're interested in implementing this change. In the meantime, I've continued to work on making this code more efficient. The current code I have runs about 20 times faster than the present implementation on large inputs. 

1. With some relatively small changes to the code (e.g. `rowSums` instead of `apply`, only call `as.matrix` once), it's ~5 times faster. 

2. A big speedup comes from changing the `estimateDc()` algorithm to use binary search instead of linear search, ~5X. 

3. By implementing a few methods in C++ using Rcpp, I can get to ~15X faster. 

4. Finally, using binary search and only doing the estimation over a subset of the distance object, the code runs >20X faster on large inputs.

Let me know what would be helpful to show you to evaluate. Two of the changes (using binary search for `estimateDc` and estimating based on a subset of the distance object) lead to slightly different results than the current implementation because the density cutoff is slightly different. Two examples from recent runs: 23685 vs 24252 or 0.795999 vs 0.8059197. But the resulting clusters and rho vs delta graphs are almost indistinguishable. The rest of the changes lead to `identical()` results from the current implementation.

**Comment by thomasp85** [comment]
Can you start by providing a PR for the changes that does not give any numerical differences (the implementation changes). For the algorithm changes (those that causes slight numerical differences I'd prefer to have a switch, defaulted to off, as the selling point of the package is an implementation of a described algorithm, and changes to the output might confuse people...

**Comment by seaaan** [comment]
Yes, I will do that. Unfortunately it's a busy week at work and I'm going
on vacation next week so it'll be a couple of weeks at the earliest. Thanks!

**Comment by seaaan** [comment]
Okay, with these commits, exact numerical equivalence is maintained with your implementation. I added a test directory with the expected results, so you can run the tests yourself and see that the results (hopefully) agree. 

Speed-up when calling `densityClust` without pre-specifying the distance cutoff (from code in  https://gist.github.com/seaaan/8120969164b5e51185a): 
```
   SecondsOld SecondsNew PercentOfOld
1        83.3        9.7         11.6
2        30.6        3.1         10.2
3         7.5        0.8         10.7
4         1.6        0.2         12.7
5         0.2        0.0         16.1
6        81.2        9.6         11.8
7        29.1        3.1         10.8
8         8.4        0.9         10.4
9         1.5        0.2         12.7
10        0.1        0.0          0.7
11        0.0        0.0          0.0
```
Speed up when calling with a pre-specified distance cutoff: 
```
   SecondsOld SecondsNew PercentOfOld
1        18.1        3.5         19.2
2         3.9        0.8         20.7
3         1.0        0.2         18.9
4         0.2        0.0         22.9
5         0.0        0.0          0.0
6        18.0        3.5         19.6
7         3.8        0.8         20.0
8         0.9        0.2         18.6
9         0.2        0.0         21.2
10        0.0        0.0         94.0
11        0.0        0.0         33.3
12       19.0        4.4         23.0
```

### Further work
As evident from the profiling, `estimateDc()` is by far the most time consuming part, taking around two-thirds of the processing time (e.g. 9.7 vs 3.5 s). The current implementation basically does linear search to find a suitable value for the distance cutoff. I wrote an alternative that uses binary search which is dramatically faster. The distance cutoff, however, will be slightly different than the one produced by the current implementation, but still within the range of `neighborRateLow` and `neighborRateHigh`. Everything else remains the same, so it's not really changing the results of the clustering algorithm, just of the estimation of the distance cutoff. I can show you that code if you're interested.

**Comment by thomasp85** [comment]
You're welcome to include the binary search into this PR - estimatDC is not really based on the article anyway so that won't be a problem...

**Comment by seaaan** [comment]
Okay, I added the binary search in. There is a test for the new DC to be within 15% of the old DC. That is arbitrary, but a sanity check. Of course it will always be within the parameters of the neighborRates. With the new implementation, the performance is: 
```
  SecondsOld SecondsNew PercentOfOld
1        64.2        3.4          5.4
2        25.6        0.8          3.1
3         7.4        0.2          2.6
4         1.4        0.0          2.3
5         0.2        0.0          8.2
6        65.6        3.5          5.3
7        26.9        0.8          3.1
8         7.4        0.2          2.6
9         1.5        0.1          4.3
10        0.1        0.0          1.1
11        0.0        0.0         48.4
```

Note: the binary search also includes subsampling the dist object to 100000 elements if it contains more than that. This means the DC varies slightly from run to run. E.g.
```
Ref: 0.2013783 
0.2461222 
0.2065002 
0.2102906 

Ref: 0.7853738 
0.8539111 
0.8365302 
0.8002971 

Ref: 1.80655 
1.865035 
1.859806 
1.903872 

Ref: 3.433145 
3.575791 
3.622733 
3.575791 

Ref: 6168.862 
6494.525 
6406.004 
6507.976 

Ref: 22947.04 
23749.94 
24105.27 
24889.35 

Ref: 55046.59 
56694.55 
57413.66 
59037.9 

Ref: 104779.8 
106322.4 
104037.2 
105673.5 
```

If you don't like that, we can remove the subsampling (or make it optional). This changes the performance to: 
```
   SecondsOld SecondsNew PercentOfOld
1        61.0        4.9          8.0
2        26.0        1.1          4.1
3         8.0        0.3          3.3
4         1.3        0.1          4.9
5         0.2        0.0          8.9
6        62.9        4.9          7.9
7        23.7        1.0          4.2
8         7.4        0.3          3.7
9         1.5        0.0          2.4
10        0.1        0.0          0.0
11        0.0        0.0          3.2
```

**Comment by seaaan** [comment]
### Further work
At this point, `estimateDc()` and `localDensity()` consume similar amounts of time (the latter becomes dominant with `gaussian = TRUE`). These could probably be further optimized, but they're already reasonably fast. 

The next thing I'd like to work on is `findClusters()`, which can be a bit slow if you have quite large objects, which are now more feasible to use. However I won't have time to work on that for several weeks.

**Comment by seaaan** [comment]
Changing the subsampling from using `sample()` to `sample.int()` is slightly faster (2X for vectors <= 4 million, 32X for vectors of 40 million elements on my computer, just for computing the indices). Taking all the other computation into account:
```
   SecondsOld SecondsNew PercentOfOld
1        76.4        3.5          4.5
2        28.9        0.8          2.8
3         7.5        0.2          2.7
4         1.6        0.1          4.1
5         0.2        0.0          8.2
6        77.5        3.6          4.6
7        30.4        0.8          2.7
8         7.8        0.2          2.4
9         1.3        0.1          4.6
10        0.1        0.0          5.1
11        0.0        0.0          7.1
```
In addition, for `estimateDc()`, I came up with a new implementation that is ~ 5X faster than the implementation based on binary search if you don't subsample (of course, they're both much slower if you don't subsample a large distance object, the new implementation is just less so). They're the same if you do subsample to 100,000 elements. So if you don't like the subsampling, let me know and I'll change the implementation.

**Comment by seaaan** [comment]
I got a chance to update the localDensity functions to work more efficiently.

**Comment by thomasp85** [comment]
I've been a bit preoccupied lately, but I'm back on full force now. I'll have a look at all your work, and if all is well, push to CRAN within a couple of days. With your permission I'll add you as contributor as this PR is substantial...

**Comment by seaaan** [comment]
Cool, that sounds great to me, thanks. I'm a bit busy lately, so haven't
done any work on `findClusters()`, but hopefully can get to it sometime.
Thanks!

**Comment by thomasp85** [comment]
My god I've been slow on this - Will submit to CRAN today

**Comment by seaaan** [comment]
Just saw that it's updated on CRAN, that's great. Thanks!

**Pull request merged**
