### PR TITLE
add plotDensityClust & cluster sorting by gamma

### PR DESCRIPTION
**Pull request by EricArcher**
Added function to use ggplot to create 1-3 part panel of decision graph, gamma graph, and/or MDS plot
Added code in findClusters to sort cluster numbers by gamma (rho * delta)

### CODE REVIEW

**Comment by EricArcher** [comment]
@thomasp85 have you had time to look at this PR? Thanks!

**Comment by thomasp85** [comment]
I have not. Real quick: is this a substitute for #7?

**Comment by EricArcher** [comment]
Yes, you had asked me to make it easier to review. It was easier to make a new PR rather than try to combine/edit commits in the previous.

**Comment by thomasp85** [comment]
Super, I'll go through it tonight...

**Comment by thomasp85** [comment]
Thanks

**Pull request merged**
